"""add role_id to users and create roles table

Revision ID: def858bcc56d
Revises: 
Create Date: 2025-10-12 12:30:08.072511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def858bcc56d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # Comentamos estas alteraciones que SQLite no soporta
    # op.alter_column('blacklisted_tokens', 'blacklisted_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.alter_column('documents', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('logs', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    # También evitamos alterar timestamps en users
    # op.alter_column('users', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('users', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=5), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    # Comentamos alter_column que SQLite no soporta
    # op.alter_column('users', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('users', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('users', 'role_id')
    # op.alter_column('logs', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('documents', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_table('roles')
    # ### end Alembic commands ###
